#**Multiple Linear Regression**
**1. Import Libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# **2. Creating Synthetic Dataset**

In [ ]:
np.random.seed() # For Reproductibility
x = np.random.rand(100,3) #
y = x[:,0] * 15000 + x[:,1] * 100000 + x[:,2] * 50000 + 50000

# **3. Converting to a DataFrame**

In [ ]:
data = pd.DataFrame(x, columns=['Size','Bedroom','Age'])
data['Price'] = y

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2,random_state=42)
data.head()

Size   Bedroom       Age          Price
0  0.597037  0.131705  0.133537   78802.939372
1  0.251994  0.227582  0.175560   85316.161637
2  0.184266  0.988028  0.380887  170611.108442
3  0.602365  0.285396  0.997780  137464.097002
4  0.214800  0.877239  0.884819  185186.804963

#**4. Initializing the Model**


In [ ]:
model = LinearRegression()

#**5. Fitting the Model**

In [ ]:
model.fit(x_train, y_train)

LinearRegression()

#**6. Making Predictions**

In [ ]:
y_predict = model.predict(x_test)
print(x_test)
print(y_predict)

[[0.12861037 0.03003276 0.469613  ]
 [0.13783832 0.53512634 0.0699682 ]
 [0.86712708 0.76242738 0.66336207]
 [0.97609582 0.69301493 0.62522555]
 [0.89955841 0.69853618 0.04106316]
 [0.64761832 0.63068894 0.79949276]
 [0.75023961 0.18533755 0.1104404 ]
 [0.27919988 0.18095676 0.20860271]
 [0.96616298 0.21153757 0.83170265]
 [0.59703737 0.13170527 0.13353704]
 [0.82691079 0.21624831 0.0818903 ]
 [0.99305687 0.32192414 0.3994168 ]
 [0.55316471 0.47241915 0.91706803]
 [0.10490655 0.86113919 0.52022619]
 [0.30691099 0.49519169 0.98331014]
 [0.21479972 0.87723875 0.88481868]
 [0.61125941 0.71242601 0.32451893]
 [0.59097475 0.92423894 0.19252175]
 [0.91515418 0.55744603 0.13699223]
 [0.30123991 0.18831189 0.62417664]]
[ 78413.08163271 109078.61850156 172417.74746452 165204.20720109
 135400.15202626 162757.80754577  85309.36943252  82713.80954622
 127231.33446151  78802.93937203  88123.00730404 117059.10681364
 151392.7868663  163698.82638478 153288.34115825 185186.8049633
 146637.43860543 160

#**7. Calculating the Mean Squared Error**

In [ ]:
mse = mean_squared_error(y_test, y_predict)
print('Mean Squared Error:', mse)

Mean Squared Error: 1.0482032722271967e-21


#**8. Predicting the Price of a New House**

In [ ]:
new_house = [[0.5,2,10]]
predicted_price = model.predict(new_house)
print('Predicted:', (predicted_price[0]))

Predicted: 757499.9999999999
